relay:
  sources:
    - id: trading_system
      path: ./test-data/trading
      file-pattern: "*.csv"
      ready-strategy: IMMEDIATE
      stability-period: 5m
      poll-interval: 30s
      enabled: true

    - id: risk_system
      path: ./test-data/risk
      file-pattern: "*.xml"
      ready-strategy: FILE_AGE
      stability-period: 2m
      poll-interval: 30s
      enabled: true

  storage:
    local:
      path: ./target/storage

  gcs:
    bucket: ${GCS_BUCKET:surveillance-data}
    project-id: ${GCP_PROJECT:lbg-surveillance}

quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:file:./target/relay-db

  hibernate-orm:
    database:
      generation: update

---
"%prod":
  quarkus:
    datasource:
      db-kind: mssql
      jdbc:
        url: jdbc:sqlserver://${DB_HOST}:1433;databaseName=${DB_NAME}